// <auto-generated />
namespace Distributor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _17th : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_17th));
        
        string IMigrationMetadata.Id
        {
            get { return "201801030935050_17th"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
